[package]
name = "alldesk-net"
version.workspace = true
edition.workspace = true

[dependencies]
alldesk-core = { path = "../alldesk-core" }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }
socket2 = "0.5"
ring = "0.17"
parking_lot = "0.12"

[build-dependencies]
prost-build = "0.13"
