// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_state`, `chat_sender_lock`, `chat_tx_lock`, `current_recorder`, `decode_special_key`, `ensure_peer_id`, `frame_rx_lock`, `frame_tx_lock`, `handle_key_event`, `handle_mouse_event`, `handle_scroll_event`, `input_transport_lock`, `install_viewer_session`, `local_ip_addresses`, `playback_lock`, `received_files_dir`, `record_pipeline_error`, `recorder_lock`, `run_adaptive_controller`, `run_input_handler`, `run_quality_sampler`, `sanitize_remote_filename`, `start_server_internal`, `supervise_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppState`, `CachedPeer`, `ClientState`, `RecordingPlayback`, `ServerState`, `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `run_file_receiver`, `send_file_session`

/// Get the library version
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();

/// Initialize the AllDesk core library. Call once at app startup.
/// Auto-starts QUIC server + background discovery broadcast/listen.
Future<String> init() => RustLib.instance.api.crateApiInit();

/// Return currently known peers from the background discovery cache.
/// When timeout_secs > 0, also performs an active broadcast scan.
Future<List<PeerInfo>> discoverPeers({required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiDiscoverPeers(timeoutSecs: timeoutSecs);

/// Start listening for incoming QUIC connections on the given port.
Future<String> startServer({required int port}) =>
    RustLib.instance.api.crateApiStartServer(port: port);

/// Connect to a remote peer via QUIC and start the receiver pipeline.
Future<String> connectToPeer({required String addr}) =>
    RustLib.instance.api.crateApiConnectToPeer(addr: addr);

/// Disconnect from current peer and stop server.
Future<String> disconnect() => RustLib.instance.api.crateApiDisconnect();

/// Get the local peer ID (stable across calls).
Future<String> getPeerId() => RustLib.instance.api.crateApiGetPeerId();

/// Simple ping for testing the bridge.
Future<String> ping({required String msg}) =>
    RustLib.instance.api.crateApiPing(msg: msg);

/// Run a diagnostic self-test: check server status, discovery socket, and local IPs.
/// Returns a multi-line diagnostic report.
Future<String> runDiagnostics() =>
    RustLib.instance.api.crateApiRunDiagnostics();

/// Start sending screen capture to the connected peer (host side).
/// NOTE: The server now auto-accepts connections in `start_server_internal()`.
/// This function is kept for backward compatibility but is no longer required.
Future<String> startScreenStream(
        {required int bitrateKbps, required int fps}) =>
    RustLib.instance.api
        .crateApiStartScreenStream(bitrateKbps: bitrateKbps, fps: fps);

/// Poll for the newest available video frame (viewer side).
/// Drains any queued frames and returns only the latest one — real-time
/// video should skip stale frames after a UI stall, not replay the backlog.
/// Returns [width_u32_le, height_u32_le, ...bgra_data] or None.
Future<Uint8List?> pollVideoFrame() =>
    RustLib.instance.api.crateApiPollVideoFrame();

/// Subscribe to a push stream of decoded video frames (viewer side).
///
/// Preferred over [`poll_video_frame`]: frames are pushed the moment they
/// are decoded (no poll-interval latency) and stale queued frames are
/// coalesced away. The stream survives reconnects — when a session ends it
/// waits for the next session's frame channel instead of completing.
Stream<VideoFrameMsg> watchVideoFrames() =>
    RustLib.instance.api.crateApiWatchVideoFrames();

/// Send a chat message to the connected peer (works on both host and viewer
/// side; each session registers its outgoing transport).
Future<void> sendChatMessage({required String text}) =>
    RustLib.instance.api.crateApiSendChatMessage(text: text);

/// Subscribe to incoming peer chat messages (push stream; survives
/// reconnects by waiting for the next session's channel, same pattern as
/// watch_video_frames).
Stream<String> watchChatMessages() =>
    RustLib.instance.api.crateApiWatchChatMessages();

/// Send a mouse event to the remote peer (viewer side).
Future<void> sendMouseEvent(
        {required double x, required double y, required String action}) =>
    RustLib.instance.api.crateApiSendMouseEvent(x: x, y: y, action: action);

/// Send a scroll event to the remote peer.
Future<void> sendScroll({required double dy}) =>
    RustLib.instance.api.crateApiSendScroll(dy: dy);

/// Send a key event to the remote peer (viewer side).
/// pressed: true = key down, false = key up.
///
/// - key_type="char": `key` is a Unicode codepoint (injected as text;
///   releases are implicit — the host sends its own down+up pair).
/// - key_type="special": `key` is a code from the shared table in
///   [`decode_special_key`] (0x01-0x09 Enter/Esc/Tab/Backspace/Delete/
///   arrows, 0x10-0x27 F1-F24, 0x30+ navigation keys, 0x40-0x47 the
///   left/right Ctrl/Shift/Alt/Meta modifiers). Keep the Dart table in
///   app/lib/services/key_mapping.dart in sync.
/// - key_type="vk": `key` is a raw Windows virtual-key code, injected
///   as-is — used for modifier combos (Ctrl+C etc.) where a char event
///   would be wrong.
Future<void> sendKeyEvent(
        {required String keyType, required int key, required bool pressed}) =>
    RustLib.instance.api
        .crateApiSendKeyEvent(keyType: keyType, key: key, pressed: pressed);

/// Get connection quality metrics and stream status.
/// Returns a JSON string with connection state, video status and real
/// transport metrics (RTT / packet loss / bandwidth) from the session sampler.
Future<String> getConnectionQuality() =>
    RustLib.instance.api.crateApiGetConnectionQuality();

/// Send a local file to the connected peer (viewer → host).
/// Returns immediately; poll progress with `get_file_transfer_status`.
Future<String> sendFileToPeer({required String path}) =>
    RustLib.instance.api.crateApiSendFileToPeer(path: path);

/// Current file transfer progress as JSON
/// ({active, direction, filename, transferred, total, error}).
Future<String> getFileTransferStatus() =>
    RustLib.instance.api.crateApiGetFileTransferStatus();

/// Start recording the remote session (VP9-encoded frames) to `path`.
Future<String> startSessionRecording({required String path}) =>
    RustLib.instance.api.crateApiStartSessionRecording(path: path);

/// Stop recording and finalize the file. Returns the output path.
Future<String> stopSessionRecording() =>
    RustLib.instance.api.crateApiStopSessionRecording();

/// Open an ALDREC recording for sequential playback. Only one recording can
/// be open at a time; opening another one replaces it.
Future<RecordingInfo> startRecordingPlayback({required String path}) =>
    RustLib.instance.api.crateApiStartRecordingPlayback(path: path);

/// Decode the next stored frame to BGRA. Returns None at the end of the
/// recording (or if no playback is open). Undecodable frames are skipped
/// with a warning so one corrupt frame can't stall playback.
Future<VideoFrameMsg?> recordingNextFrame() =>
    RustLib.instance.api.crateApiRecordingNextFrame();

/// Rewind the open playback to the first frame.
Future<void> rewindRecordingPlayback() =>
    RustLib.instance.api.crateApiRewindRecordingPlayback();

/// Close the open playback session.
Future<void> stopRecordingPlayback() =>
    RustLib.instance.api.crateApiStopRecordingPlayback();

/// Stub for non-Android platforms.
bool pushAndroidFrame(
        {required List<int> bgraData,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiPushAndroidFrame(
        bgraData: bgraData, width: width, height: height);

/// Get Android frame capture statistics: (frames_received, frames_dropped).
(BigInt, BigInt) getAndroidFrameStats() =>
    RustLib.instance.api.crateApiGetAndroidFrameStats();

/// Stop all streaming (both sender and receiver).
Future<String> stopStream() => RustLib.instance.api.crateApiStopStream();

/// Progress of an ongoing file transfer, surfaced to Flutter as JSON.
class FileTransferProgress {
  final bool active;
  final String direction;
  final String filename;
  final BigInt transferred;
  final BigInt total;
  final String? error;

  const FileTransferProgress({
    required this.active,
    required this.direction,
    required this.filename,
    required this.transferred,
    required this.total,
    this.error,
  });

  static Future<FileTransferProgress> default_() =>
      RustLib.instance.api.crateApiFileTransferProgressDefault();

  @override
  int get hashCode =>
      active.hashCode ^
      direction.hashCode ^
      filename.hashCode ^
      transferred.hashCode ^
      total.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileTransferProgress &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          direction == other.direction &&
          filename == other.filename &&
          transferred == other.transferred &&
          total == other.total &&
          error == other.error;
}

/// A discovered peer on the LAN
class PeerInfo {
  final String peerId;
  final String peerName;
  final String address;

  const PeerInfo({
    required this.peerId,
    required this.peerName,
    required this.address,
  });

  @override
  int get hashCode => peerId.hashCode ^ peerName.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          address == other.address;
}

/// Metadata of a recording opened for playback.
class RecordingInfo {
  final int width;
  final int height;
  final int fps;
  final int frameCount;
  final BigInt durationMs;

  const RecordingInfo({
    required this.width,
    required this.height,
    required this.fps,
    required this.frameCount,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fps.hashCode ^
      frameCount.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordingInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fps == other.fps &&
          frameCount == other.frameCount &&
          durationMs == other.durationMs;
}

/// One decoded video frame pushed to Flutter (viewer side).
class VideoFrameMsg {
  final int width;
  final int height;
  final Uint8List bgra;

  const VideoFrameMsg({
    required this.width,
    required this.height,
    required this.bgra,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ bgra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFrameMsg &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bgra == other.bgra;
}
