// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_state`, `ensure_peer_id`, `local_ip_addresses`, `start_server_internal`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AppState`, `CachedPeer`, `ClientState`, `ServerState`, `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Get the library version
Future<String> getVersion() => RustLib.instance.api.crateApiGetVersion();

/// Initialize the AllDesk core library. Call once at app startup.
/// Auto-starts QUIC server + background discovery broadcast/listen.
Future<String> init() => RustLib.instance.api.crateApiInit();

/// Return currently known peers from the background discovery cache.
Future<List<PeerInfo>> discoverPeers({required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiDiscoverPeers(timeoutSecs: timeoutSecs);

/// Start listening for incoming QUIC connections on the given port.
Future<String> startServer({required int port}) =>
    RustLib.instance.api.crateApiStartServer(port: port);

/// Connect to a remote peer via QUIC and start the receiver pipeline.
Future<String> connectToPeer({required String addr}) =>
    RustLib.instance.api.crateApiConnectToPeer(addr: addr);

/// Disconnect from current peer and stop server.
Future<String> disconnect() => RustLib.instance.api.crateApiDisconnect();

/// Get the local peer ID (stable across calls).
Future<String> getPeerId() => RustLib.instance.api.crateApiGetPeerId();

/// Simple ping for testing the bridge.
Future<String> ping({required String msg}) =>
    RustLib.instance.api.crateApiPing(msg: msg);

/// Run a diagnostic self-test: check server status, discovery socket, and local IPs.
/// Returns a multi-line diagnostic report.
Future<String> runDiagnostics() =>
    RustLib.instance.api.crateApiRunDiagnostics();

/// Start sending screen capture to the connected peer (host side).
Future<String> startScreenStream(
        {required int bitrateKbps, required int fps}) =>
    RustLib.instance.api
        .crateApiStartScreenStream(bitrateKbps: bitrateKbps, fps: fps);

/// Poll for the next available video frame (viewer side).
/// Returns [width_u32_le, height_u32_le, ...bgra_data] or None.
Future<Uint8List?> pollVideoFrame() =>
    RustLib.instance.api.crateApiPollVideoFrame();

/// Send a mouse event to the remote peer (viewer side).
Future<void> sendMouseEvent(
        {required double x, required double y, required String action}) =>
    RustLib.instance.api.crateApiSendMouseEvent(x: x, y: y, action: action);

/// Send a scroll event to the remote peer.
Future<void> sendScroll({required double dy}) =>
    RustLib.instance.api.crateApiSendScroll(dy: dy);

/// Stub for non-Android platforms.
Future<void> pushAndroidFrame(
        {required List<int> bgraData,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiPushAndroidFrame(
        bgraData: bgraData, width: width, height: height);

/// Stop all streaming (both sender and receiver).
Future<String> stopStream() => RustLib.instance.api.crateApiStopStream();

/// A discovered peer on the LAN
class PeerInfo {
  final String peerId;
  final String peerName;
  final String address;

  const PeerInfo({
    required this.peerId,
    required this.peerName,
    required this.address,
  });

  @override
  int get hashCode => peerId.hashCode ^ peerName.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          address == other.address;
}
