[package]
name = "alldesk-clipboard"
version.workspace = true
edition.workspace = true

[dependencies]
alldesk-core = { path = "../alldesk-core" }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
cfg-if = { workspace = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = { workspace = true }
